# File: CheckEasyBackend/environment.yml
name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - easyocr=1.7.2
  - spacy=3.8.2
  - pytesseract=0.3.10
  - pillow=9.5.0
  - aiofiles=24.1.0
  - alembic=1.15.1
  - celery=5.4.0
  - fastapi=0.115.11
  - sqlalchemy=2.0.38
  - redis
  - python-dotenv=1.0.1
  - pip
  - pip:
      - amqp==5.3.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asyncpg==0.30.0
      - bcrypt==4.3.0
      - billiard==4.2.1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - dnspython==2.7.0
      - email_validator==2.2.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - iniconfig==2.0.0
      - Jinja2==3.1.5
      - kombu==5.4.2
      - Mako==1.3.9
      - MarkupSafe==3.0.2
      - packaging==24.2
      - passlib==1.7.4
      - pluggy==1.5.0
      - prompt_toolkit==3.0.50
      - psycopg2-binary==2.9.10
      - pydantic==2.10.6
      - pydantic_core==2.27.2
      - PyJWT==2.10.1
      - PyMySQL==1.1.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - requests==2.32.3
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.0
      - typing_extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - vine==5.1.0
      - wcwidth==0.2.13